spring.datasource.url=jdbc:postgresql://dpg-d21ohjm3jp1c7384e690-a/expense_db_tq8y
spring.datasource.username=expense_user
spring.datasource.password=cFvzXzdNPRTCeMffZJJ4k8Dq7Z4F8wAh
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true